---
title: "Graphs"
author: "Anastasia Bernat"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())

library(rethinking)
library(dplyr)
library(rstatix)
library(ggplot2)
library(ggpubr)

dir = "/Users/anastasiabernat/Desktop/git_repositories/ocotillo-research/"
#dir = "/Users/allegrasteenson/Desktop/ocotillo-research/"
setwd(dir)

knitr::opts_chunk$set(echo = TRUE)
```

## Reading and Cleaning the Data

```{r}
source("src/cleaning_data.R")
source("src/regression_output.R")
output_col = FALSE

all_data = clean_data("data/General_Oco_Data.csv", "data/End_Segments_5segs.csv")

ocos = all_data[[2]]
ocos_baj = ocos[ocos$Plant[1:20],]

seg_baj = all_data[[1]][[1]]
segs = all_data[[1]][[3]]

segs <- segs[!is.na(segs$Length_c),]
```

## Shared Plotting Parameters

```{r}
c1 = 1.2 * 1.2
c2 = 1.3 * 1.2
c3 = 1.5 * 1.2
c4 = 1.1 * 1.2
```

## Height

```{r fig.width=2.1, fig.height=5.18}

par(mfrow=c(3,1))

###### Plot A

d = ocos
x=d[,"Elevation_c"]
y=d[,"logHeight"] 

m <- lm(logHeight ~ Elevation_c, data=ocos)
x.seq = seq(min(x) - sd(x), max(x) + sd(x), length.out=100)
m <- lm(y ~ x, data=ocos)
prd <- data.frame(x=x.seq) 
err <- predict(m, newdata = prd, se.fit = TRUE)
prd$lci <- err$fit - 1.96 * err$se.fit
prd$fit <- err$fit
prd$uci <- err$fit + 1.96 * err$se.fit
mu_ci <- t(matrix(c(prd$lci,prd$uci), ncol=2))

par(mar = c(5, 5, 2, 0)) 
colfunc <- colorRampPalette(c("red", "orange"))
plot(ocos$logHeight ~ ocos$Elevation_c, 
     col=colfunc(2)[as.factor(ocos$site)], 
     pch = c(17:16)[as.factor(ocos$site)],
     xlab = "Elevation (m)",
     ylab= "Log(Height) (m)", 
     cex=c2,
     cex.lab=c3,
     cex.axis=c2,
     bty="n",
     xlim=c(-50, 40)
     ) 
legend(3,1.58,
       legend = c("Bajada", "Plain"),
       col= c(colfunc(2)[1], colfunc(2)[2]),
       pch = c(17:16),
       cex=c4,
       title="Site Type")
abline(m, lty=2)
shade(mu_ci, lim = prd$x)
pval <- paste0("p = ", round(summary(m)$coefficients[8],3), "*")
text(-16, 1.4, pval, cex=c1)
title("(a)", adj = 0.05, line = 0, cex.main=c3)

###### Plot B

d = ocos
x=d[,"TSeg_c"]
y=d[,"logHeight"] 

m <- lm(logHeight ~ TSeg_c, data=ocos)
x.seq = seq(min(x) - sd(x), max(x) + sd(x), length.out=100)
m <- lm(y ~ x, data=ocos)
prd <- data.frame(x=x.seq) # newdata
err <- predict(m, newdata = prd, se.fit = TRUE)
prd$lci <- err$fit - 1.96 * err$se.fit
prd$fit <- err$fit
prd$uci <- err$fit + 1.96 * err$se.fit
mu_ci <- t(matrix(c(prd$lci,prd$uci), ncol=2))

colfunc <- colorRampPalette(c("red", "orange"))
plot(ocos$logHeight ~ ocos$TSeg_c, 
     col=colfunc(2)[as.factor(ocos$site)], 
     pch = c(17:16)[as.factor(ocos$site)],
     xlab = "Terminal Segment Length IQR (cm)",
     ylab= "Log(Height) (m)", 
     cex=c2,
     cex.lab=c3,
     cex.axis=c2,
     bty="n") 
legend(7,1,
       legend = c("Bajada", "Plain"),
       col= c(colfunc(2)[1], colfunc(2)[2]),
       pch = c(17:16),
       cex=c4,
       title="Site Type")
abline(m, lty=2)
shade(mu_ci, lim = prd$x)
pval <- paste0("p = ", round(summary(m)$coefficients[8],3), "*")
text(7, 1.1, pval, cex=c1)
title("(b)", adj = 0.05, line = 0, cex.main=c3)

###### Plot C

par(bty = 'n')
boxplot(Height~site,
        data=ocos,
        xlab = "Site",
        ylab= "Height (m)",
        col=c(col.alpha( "red" , alpha = 0.4 ), 
              col.alpha( "orange" , alpha = 0.4)),
        border="gray30",
        names=c("Bajada", "Plain"),
     cex=c2,
     cex.lab=c3,
     cex.axis=c2
)
title("(c)", adj = 0.05, line = 0, cex.main=c3)
```

```{r fig.width=3.0, fig.height=2.9}

###### Plot B Pooled by Site

dB <- ocos %>%
  filter(site==0)
dP <- ocos %>%
  filter(site==1)

xB=dB[,"TSeg_c"]
yB=dB[,"logHeight"] 
xP=dP[,"TSeg_c"]
yP=dP[,"logHeight"] 

mB <- lm(yB ~ xB, data=dB)
mP <- lm(yP ~ xP, data=dP)
xB.seq = seq(min(xB) - sd(xB), max(xB) + sd(xB)*2, length.out=100)
xP.seq = seq(min(xP) - 2*sd(xP), max(xP) + sd(xP), length.out=100)

prdB <- data.frame(xB=xB.seq) # newdata
prdP <- data.frame(xP=xP.seq) # newdata

errB <- predict(mB, newdata = prdB, se.fit = TRUE)
errP <- predict(mP, newdata = prdP, se.fit = TRUE)

prdB$lciB <- errB$fit - 1.96 * errB$se.fit
prdP$lciP <- errP$fit - 1.96 * errP$se.fit

prdB$fit <- errB$fit
prdP$fit <- errP$fit

prdB$uci <- errB$fit + 1.96 * errB$se.fit
prdP$uci <- errP$fit + 1.96 * errP$se.fit

mu_ciB <- t(matrix(c(prdB$lci,prdB$uci), ncol=2))
mu_ciP <- t(matrix(c(prdP$lci,prdP$uci), ncol=2))

colfunc <- colorRampPalette(c("red", "orange"))
plot(ocos$logHeight ~ ocos$TSeg_c, 
     col=colfunc(2)[as.factor(ocos$site)], 
     pch = c(17:16)[as.factor(ocos$site)],
     xlab = "Terminal Segment Length IQR (cm)",
     ylab= "Log(Height)", 
     cex=c2,
     cex.lab=c3,
     cex.axis=c2,
     bty="n"
     ) 
legend(7, 1,
       legend = c("Bajada", "Plain"),
       col= c(colfunc(2)[1],colfunc(2)[2] ),
       #bty="n",
       pch = c(17:16),
       cex=c1,
       title="Site Type"
       )
abline(mB, lty=2, col="red")
abline(mP, lty=2, col="darkorange")
shade(mu_ciB, lim = prdB$xB, col=col.alpha("darkred"))
shade(mu_ciP, lim = prdP$xP, col=col.alpha("orange"))
pvalB <- paste0("p = ", round(summary(mB)$coefficients[8],3), "*")
pvalP <- paste0("p = ", round(summary(mP)$coefficients[8],3))
text(5, 1, pvalB, cex=c1, col="red")
text(-3, 1.4, pvalP, cex=c1, col="darkorange")
title("(b)", adj = 0.05, line = 0, cex.main=c3)
summary(mB)
summary(mP)
```

## Circumference and Number of Branches

```{r fig.width=2.1, fig.height=5.18}

par(mfrow=c(3,1))
par(mar = c(4, 5, 2, 0)) 

###### Plot A

dN <- ocos %>%
  filter(COMP_plant_b==0)
dS <- ocos %>%
  filter(COMP_plant_b==1)

xN=dN[,"Circ_c"]
yN=dN[,"logNB"] 
xS=dS[,"Circ_c"]
yS=dS[,"logNB"] 

mN <- lm(yN ~ xN, data=dN)
mS <- lm(yS ~ xS, data=dS)
xN.seq = seq(min(xN) - sd(xN), max(xN) + sd(xN)*2, length.out=100)
xS.seq = seq(min(xS) - sd(xS), max(xS) + sd(xS), length.out=100)

prdN <- data.frame(xN=xN.seq) # newdata
prdS <- data.frame(xS=xS.seq) # newdata

errN <- predict(mN, newdata = prdN, se.fit = TRUE)
errS <- predict(mS, newdata = prdS, se.fit = TRUE)

prdN$lciN <- errN$fit - 1.96 * errN$se.fit
prdS$lciS <- errS$fit - 1.96 * errS$se.fit

prdN$fit <- errN$fit
prdS$fit <- errS$fit

prdN$uci <- errN$fit + 1.96 * errN$se.fit
prdS$uci <- errS$fit + 1.96 * errS$se.fit

mu_ciN <- t(matrix(c(prdN$lci,prdN$uci), ncol=2))
mu_ciS <- t(matrix(c(prdS$lci,prdS$uci), ncol=2))

colfunc <- colorRampPalette(c("blue", "red"))
plot(ocos$logNB ~ ocos$Circ_c, 
     col=colfunc(2)[as.factor(ocos$COMP_plant_type)], 
     pch = c(17:16)[as.factor(ocos$COMP_plant_type)],
     xlab = "Circumference (m)",
     ylab= "Log(Number of Branches)", 
     cex=c2,
     cex.lab=c3,
     cex.axis=c2,
     bty="n",
     ylim=c(2,4.1),
     xlim=c(-3,4)
     ) 
legend(1.5, 2.65,
       legend = c("Cactus", "Shrub"),
       col= c(colfunc(2)[1],colfunc(2)[2] ),
       #bty="n",
       pch = c(17:16),
       cex=c1
       )
abline(mN, lty=2, col="darkblue")
abline(mS, lty=2, col="red")
shade(mu_ciN, lim = prdN$xN, col=col.alpha("darkblue"))
shade(mu_ciS, lim = prdS$xS, col=col.alpha("red"))
pvalN <- paste0("p = ", round(summary(mN)$coefficients[8],3))
pvalS <- paste0("p = ", round(summary(mS)$coefficients[8],3), "*")
text(0.3, 3.7, pvalN, cex=c1, col="darkblue")
text(1.5, 2.9, pvalS, cex=c1, col="red")
title("(a)", adj = 0.05, line = 0, cex.main=c3)


###### Plot B

d = ocos
x=d[,"Arroyo_Dis"]
y=d[,"logNB"] 

x.seq = seq(min(x) - sd(x), max(x) + sd(x), length.out=100)
m <- lm(y ~ x, data=ocos)
prd <- data.frame(x=x.seq) # newdata
err <- predict(m, newdata = prd, se.fit = TRUE)
prd$lci <- err$fit - 1.96 * err$se.fit
prd$fit <- err$fit
prd$uci <- err$fit + 1.96 * err$se.fit
mu_ci <- t(matrix(c(prd$lci,prd$uci), ncol=2))

colfunc <- colorRampPalette(c("blue", "orange"))
plot(ocos$logNB ~ ocos$Arroyo_Dis, 
     pch=16,
     xlab = "Distance to the Nearest Arroyo (m)",
     ylab= "Log(Number of Branches)", 
     cex=c2,
     cex.lab=c3,
     cex.axis=c2,
     bty="n"
     ) 
abline(m, lty=2)
shade(mu_ci, lim = prd$x)
pval <- paste0("p = ", round(summary(m)$coefficients[8],3), "*")
text(50, 3.0, pval, cex=c1)
title("(b)", adj = 0.05, line = 0, cex.main=c3)

###### Plot C

par(bty = 'n')
boxplot(logNB~COMP_plant_b,
        data=ocos,
        xlab = "Major Interspecific Plant Group",
        ylab= "Log(Number of Branches)",
        col=c(col.alpha( "blue" , alpha = 0.35 ), 
              col.alpha( "red" , alpha = 0.35)),
        border=c("grey28", "grey28"), # grey30 # darkblue, red
        names=c("Cactus", "Shrub"),
     cex=c2,
     cex.lab=c3,
     cex.axis=c2
)
title("(c)", adj = 0.05, line = 0, cex.main=c3)
```

## Nearest Neighbor

```{r fig.width=6, fig.height=2.7}
par(mfrow=c(1,2))

###### Plot A

d = ocos_baj
x=d[,"Elevation"]
y=d[,"logNN"] 

m <- lm(y ~ x, data=d)
x.seq = seq(min(x) - sd(x), max(x) + 2*sd(x), length.out=100)

prd <- data.frame(x=x.seq)
err <- predict(m, newdata = prd, se.fit = TRUE)
prd$lci <- err$fit - 1.96 * err$se.fit
prd$fit <- err$fit
prd$uci <- err$fit + 1.96 * err$se.fit
mu_ci <- t(matrix(c(prd$lci,prd$uci), ncol=2))

plot(ocos_baj$logNN ~ ocos_baj$Elevation, 
     pch=(16),
     xlab = "Elevation (m)",
     ylab= "Log(Distance to Nearest Neighbor) (m)", 
     cex=1.3,
     cex.lab=1.5,
     cex.axis=1.3,
     bty="n",
     xlim=c(520,600),
     ylim=c(0,3.5)
     ) 
abline(m, lty=2)
 
shade(mu_ci, lim = prd$x)
pval <- paste0("p = ", round(summary(m)$coefficients[8],3), "*")
text(560, 3, pval, cex=c1)
title("(a)", adj = 0.05, line = 0, cex.main=c3)

###### Plot B

d = ocos_baj
x=d[,"Number_Branches"]
y=d[,"logNN"] 

m <- lm(y ~ x, data=d)
x.seq = seq(min(x) - sd(x), max(x) + sd(x), length.out=100)

prd <- data.frame(x=x.seq) 
err <- predict(m, newdata = prd, se.fit = TRUE)
prd$lci <- err$fit - 1.96 * err$se.fit
prd$fit <- err$fit
prd$uci <- err$fit + 1.96 * err$se.fit
mu_ci <- t(matrix(c(prd$lci,prd$uci), ncol=2))

colfunc <- colorRampPalette(c("grey", "black"))
plot(ocos_baj$logNN ~ ocos_baj$Number_Branches, 
     col=colfunc(20)[as.factor(ocos_baj$COMP_dis)], 
     pch=(16),
     xlab = "Number of Branches",
     ylab= "Log(Distance to Nearest Neighbor) (m)", 
     cex=1.3,
     cex.lab=1.5,
     cex.axis=1.3,
     bty="n",
     xlim=c(10,60),
     ylim=c(0,3)
     ) 
legend(40, 1.5,
       legend = c("0-11", "11-22", "22-33", "33-44", "44-55"),
       col= c(colfunc(20)[1], colfunc(20)[5], colfunc(20)[9], colfunc(20)[13], colfunc(20)[20]),
       #bty="n",
       pch = c(16),
       cex=1.2,
       title="Interspecific Distance")
abline(m, lty=2)
shade(mu_ci, lim = prd$x)
pval <- paste0("p = ", round(summary(m)$coefficients[8],3), "*")
text(32, 1.3, pval, cex=c1)
title("(b)", adj = 0.05, line = 0, cex.main=c3)
```

## Terminal Segment Lengths

```{r}
d = data.frame(Length=segs$Length, 
               Tree = as.character(segs$Tree),
               site = as.character(segs$site))
data = d[d$Tree != 1,]
pwc <- segs %>% 
  dunn_test(Length ~ Tree, p.adjust.method = "bonferroni")
pwc <- pwc %>% add_xy_position(x = "group")

res.kruskal <- segs %>% kruskal_test(Length ~ Tree)
res.kruskal

ggplot(data, aes(Tree,Length, color=site)) + 
  geom_violin() +
    labs(
    subtitle = get_test_label(res.kruskal, detailed = TRUE),
    caption = get_pwc_label(pwc)
    ) +
  theme(legend.position="none") +
  xlab("Ocotillo Number") +
  ylab("Terminal Segment Length (cm)") 
# +
#   geom_boxplot(width=0.1) 
# +
#   stat_pvalue_manual(pwc, hide.ns = TRUE)
```

```{r}
pwc <- segs %>% 
  dunn_test(Length ~ site, p.adjust.method = "bonferroni")
pwc <- pwc %>% add_xy_position(x = "group")

res.kruskal <- segs %>% kruskal_test(Length ~ site)
res.kruskal

ggplot(data, aes(site,Length, color=site)) + 
  geom_violin() +
    labs(
    subtitle = get_test_label(res.kruskal, detailed = TRUE),
    caption = get_pwc_label(pwc)
    ) +
  theme(legend.position="none") +
  xlab("Site") +
  ylab("Terminal Segment Length (cm)") +
  geom_boxplot(width=0.1) +
  stat_pvalue_manual(pwc, hide.ns = TRUE)
```

```{r}
qqnorm(segs$Length, pch = 1, frame = FALSE)
qqline(segs$Length, col = "steelblue", lwd = 2)

qqnorm(ocos$Terminal_SegIQR, pch = 1, frame = FALSE)
qqline(ocos$Terminal_SegIQR, col = "steelblue", lwd = 2)
```

```{r}
Tree1 = segs[segs$Tree == 1,]
Tree2 = segs[segs$Tree == 2,]
Tree3 = segs[segs$Tree == 3,]
Tree4 = segs[segs$Tree == 4,]
Tree5 = segs[segs$Tree == 5,]
Tree6 = segs[segs$Tree == 6,]
Tree7 = segs[segs$Tree == 7,]
Tree8 = segs[segs$Tree == 8,]
Tree9 = segs[segs$Tree == 9,]
Tree10 = segs[segs$Tree == 10,]

Tree11 = segs[segs$Tree == 11,]
Tree12 = segs[segs$Tree == 12,]
Tree13 = segs[segs$Tree == 13,]
Tree14 = segs[segs$Tree == 14,]
Tree15 = segs[segs$Tree == 15,]
Tree16 = segs[segs$Tree == 16,]
Tree17 = segs[segs$Tree == 17,]
Tree18 = segs[segs$Tree == 18,]
Tree19 = segs[segs$Tree == 19,]
Tree20 = segs[segs$Tree == 20,]

Tree21 = segs[segs$Tree == 21,]
Tree22 = segs[segs$Tree == 22,]
Tree23 = segs[segs$Tree == 23,]
Tree24 = segs[segs$Tree == 24,]
Tree25 = segs[segs$Tree == 25,]

Tree26 = segs[segs$Tree == 26,]
Tree27 = segs[segs$Tree == 27,]
```


```{r fig.height=3, fig.width=3}
qs = seq(0.05, 1, 0.05)
y <- quantile(Tree2$Length, qs, type = 5)
x <- qnorm( qs )
#y2 <- quantile(Tree1$Length, qs, type = 5)
y3 <- quantile(Tree3$Length, qs, type = 5)
y4 <- quantile(Tree4$Length, qs, type = 5)
y5 <- quantile(Tree5$Length, qs, type = 5)
y6 <- quantile(Tree6$Length, qs, type = 5)
y7 <- quantile(Tree7$Length, qs, type = 5)
y8 <- quantile(Tree8$Length, qs, type = 5)
y9 <- quantile(Tree9$Length, qs, type = 5)
y10 <- quantile(Tree10$Length, qs, type = 5)

y11 <- quantile(Tree11$Length, qs, type = 5)
y12 <- quantile(Tree12$Length, qs, type = 5)
y13 <- quantile(Tree13$Length, qs, type = 5)
y14 <- quantile(Tree14$Length, qs, type = 5)
y15 <- quantile(Tree15$Length, qs, type = 5)
y16 <- quantile(Tree16$Length, qs, type = 5)
y17 <- quantile(Tree17$Length, qs, type = 5)
y18 <- quantile(Tree18$Length, qs, type = 5)
y19 <- quantile(Tree19$Length, qs, type = 5)
y20 <- quantile(Tree20$Length, qs, type = 5)

y21 <- quantile(Tree21$Length, qs, type = 5)
y22 <- quantile(Tree22$Length, qs, type = 5)
y23 <- quantile(Tree23$Length, qs, type = 5)
y24 <- quantile(Tree24$Length, qs, type = 5)
y25 <- quantile(Tree25$Length, qs, type = 5)
y26 <- quantile(Tree26$Length, qs, type = 5)
y27 <- quantile(Tree27$Length, qs, type = 5)

slope <- diff(y) / diff(x)
int <- y[1] - slope * x[1]

par(bty = 'n')
plot(x, y, col="grey", ylim=c(0,40), type="l",
     ylab="Terminal Segment Length Quantiles",
     xlab="Theoretical Quantile")
lines(x, y3, col="grey")
lines(x, y4, col="grey")
lines(x, y5, col="grey")
lines(x, y6, col="grey")
lines(x, y7, col="grey")
lines(x, y8, col="grey")
lines(x, y9, col="grey")
lines(x, y10, col="grey")

lines(x, y11, col="grey")
lines(x, y12, col="grey")
lines(x, y13, col="grey")
lines(x, y14, col="grey")
lines(x, y15, col="grey")
lines(x, y16, col="grey")
lines(x, y17, col="grey")
lines(x, y18, col="grey")
lines(x, y19, col="grey")
lines(x, y20, col="grey")

lines(x, y21, col="blue")
lines(x, y22, col="blue")
lines(x, y23, col="blue")
lines(x, y24, col="blue")
lines(x, y25, col="blue")
lines(x, y26, col="blue")
lines(x, y27, col="blue")

abline(a=int, b=slope)
```


## Try

Gather the shortest seg of each ocotillo on each branch and compare to the longest seg of each ocotillo on each branch.

```{r}
max1 = tapply(X=Tree1$Length, INDEX=Tree1$branch_num, FUN=max, na.rm=T)
max2 = tapply(X=Tree2$Length, INDEX=Tree2$branch_num, FUN=max, na.rm=T)
max3 = tapply(X=Tree3$Length, INDEX=Tree3$branch_num, FUN=max, na.rm=T)
max4 = tapply(X=Tree4$Length, INDEX=Tree4$branch_num, FUN=max, na.rm=T)
max5 = tapply(X=Tree5$Length, INDEX=Tree5$branch_num, FUN=max, na.rm=T)
max6 = tapply(X=Tree6$Length, INDEX=Tree6$branch_num, FUN=max, na.rm=T)
max7 = tapply(X=Tree7$Length, INDEX=Tree7$branch_num, FUN=max, na.rm=T)
max8 = tapply(X=Tree8$Length, INDEX=Tree8$branch_num, FUN=max, na.rm=T)
max9 = tapply(X=Tree9$Length, INDEX=Tree9$branch_num, FUN=max, na.rm=T)
max10 = tapply(X=Tree10$Length, INDEX=Tree10$branch_num, FUN=max, na.rm=T)

max11 = tapply(X=Tree11$Length, INDEX=Tree11$branch_num, FUN=max, na.rm=T)
max12 = tapply(X=Tree12$Length, INDEX=Tree12$branch_num, FUN=max, na.rm=T)
max13 = tapply(X=Tree13$Length, INDEX=Tree13$branch_num, FUN=max, na.rm=T)
max14 = tapply(X=Tree14$Length, INDEX=Tree14$branch_num, FUN=max, na.rm=T)
max15 = tapply(X=Tree15$Length, INDEX=Tree15$branch_num, FUN=max, na.rm=T)
max16 = tapply(X=Tree16$Length, INDEX=Tree16$branch_num, FUN=max, na.rm=T)
max17 = tapply(X=Tree17$Length, INDEX=Tree17$branch_num, FUN=max, na.rm=T)
max18 = tapply(X=Tree18$Length, INDEX=Tree18$branch_num, FUN=max, na.rm=T)
max19 = tapply(X=Tree19$Length, INDEX=Tree19$branch_num, FUN=max, na.rm=T)
max20 = tapply(X=Tree20$Length, INDEX=Tree20$branch_num, FUN=max, na.rm=T)

max21 = tapply(X=Tree21$Length, INDEX=Tree21$branch_num, FUN=max, na.rm=T)
max22 = tapply(X=Tree22$Length, INDEX=Tree22$branch_num, FUN=max, na.rm=T)
max23 = tapply(X=Tree23$Length, INDEX=Tree23$branch_num, FUN=max, na.rm=T)
max24 = tapply(X=Tree24$Length, INDEX=Tree24$branch_num, FUN=max, na.rm=T)
max25 = tapply(X=Tree25$Length, INDEX=Tree25$branch_num, FUN=max, na.rm=T)
max26 = tapply(X=Tree26$Length, INDEX=Tree26$branch_num, FUN=max, na.rm=T)
max27 = tapply(X=Tree27$Length, INDEX=Tree27$branch_num, FUN=max, na.rm=T)

length = c(max1, max2, max3, max4, max5, max6, max7, max8, max9, max10,
                      max11, max12, max13, max14, max15, max16, max17, max18, max19, max20,
                      max21, max22, max23, max24, max25, max26, max27)
high = as.data.frame(cbind(length))
high$site = 0
high$site[1:200] <- "bajada"
high$site[201:270] <- "plain"
high$extreme = 0
high$extreme[1:270] <- "max"
high
```

```{r}
min1 = tapply(X=Tree1$Length, INDEX=Tree1$branch_num, FUN=min, na.rm=T)
min2 = tapply(X=Tree2$Length, INDEX=Tree2$branch_num, FUN=min, na.rm=T)
min3 = tapply(X=Tree3$Length, INDEX=Tree3$branch_num, FUN=min, na.rm=T)
min4 = tapply(X=Tree4$Length, INDEX=Tree4$branch_num, FUN=min, na.rm=T)
min5 = tapply(X=Tree5$Length, INDEX=Tree5$branch_num, FUN=min, na.rm=T)
min6 = tapply(X=Tree6$Length, INDEX=Tree6$branch_num, FUN=min, na.rm=T)
min7 = tapply(X=Tree7$Length, INDEX=Tree7$branch_num, FUN=min, na.rm=T)
min8 = tapply(X=Tree8$Length, INDEX=Tree8$branch_num, FUN=min, na.rm=T)
min9 = tapply(X=Tree9$Length, INDEX=Tree9$branch_num, FUN=min, na.rm=T)
min10 = tapply(X=Tree10$Length, INDEX=Tree10$branch_num, FUN=min, na.rm=T)

min11 = tapply(X=Tree11$Length, INDEX=Tree11$branch_num, FUN=min, na.rm=T)
min12 = tapply(X=Tree12$Length, INDEX=Tree12$branch_num, FUN=min, na.rm=T)
min13 = tapply(X=Tree13$Length, INDEX=Tree13$branch_num, FUN=min, na.rm=T)
min14 = tapply(X=Tree14$Length, INDEX=Tree14$branch_num, FUN=min, na.rm=T)
min15 = tapply(X=Tree15$Length, INDEX=Tree15$branch_num, FUN=min, na.rm=T)
min16 = tapply(X=Tree16$Length, INDEX=Tree16$branch_num, FUN=min, na.rm=T)
min17 = tapply(X=Tree17$Length, INDEX=Tree17$branch_num, FUN=min, na.rm=T)
min18 = tapply(X=Tree18$Length, INDEX=Tree18$branch_num, FUN=min, na.rm=T)
min19 = tapply(X=Tree19$Length, INDEX=Tree19$branch_num, FUN=min, na.rm=T)
min20 = tapply(X=Tree20$Length, INDEX=Tree20$branch_num, FUN=min, na.rm=T)

min21 = tapply(X=Tree21$Length, INDEX=Tree21$branch_num, FUN=min, na.rm=T)
min22 = tapply(X=Tree22$Length, INDEX=Tree22$branch_num, FUN=min, na.rm=T)
min23 = tapply(X=Tree23$Length, INDEX=Tree23$branch_num, FUN=min, na.rm=T)
min24 = tapply(X=Tree24$Length, INDEX=Tree24$branch_num, FUN=min, na.rm=T)
min25 = tapply(X=Tree25$Length, INDEX=Tree25$branch_num, FUN=min, na.rm=T)
min26 = tapply(X=Tree26$Length, INDEX=Tree26$branch_num, FUN=min, na.rm=T)
min27 = tapply(X=Tree27$Length, INDEX=Tree27$branch_num, FUN=min, na.rm=T)

length = c(min1, min2, min3, min4, min5, min6, min7, min8, min9, min10,
                      min11, min12, min13, min14, min15, min16, min17, min18, min19, min20,
                      min21, min22, min23, min24, min25, min26, min27)

low = as.data.frame(cbind(length))
low$site = 0
low$site[1:200] <- "bajada"
low$site[201:270] <- "plain"
low$extreme = 0
low$extreme[1:270] <- "min"
low
```

```{r}
df = rbind(high, low)
df
```

```{r fig.width=2.1, fig.height=5.18}

par(mfrow=c(3,1))

par(bty = 'n')
boxplot(length~site,
        data=high,
        xlab = "Site",
        ylab= "Terminal Segment Length (cm)",
        col=c(col.alpha( "red" , alpha = 0.4 ), 
              col.alpha( "orange" , alpha = 0.4)),
        border="gray30",
        names=c("Bajada", "Plain"),
     cex=c2,
     cex.lab=c3,
     cex.axis=c2
)
title("(a)", adj = 0.05, line = 0, cex.main=c3)

boxplot(length~site,
        data=low,
        xlab = "Site",
        ylab= "Terminal Segment Length (cm)",
        col=c(col.alpha( "red" , alpha = 0.4 ), 
              col.alpha( "orange" , alpha = 0.4)),
        border="gray30",
        names=c("Bajada", "Plain"),
     cex=c2,
     cex.lab=c3,
     cex.axis=c2
)
title("(b)", adj = 0.05, line = 0, cex.main=c3)


boxplot(length~extreme,
        data=df,
        xlab = "Extreme Values",
        ylab= "Terminal Segment Length (cm)",
        col=c(col.alpha( "red" , alpha = 0.4 ), 
              col.alpha( "orange" , alpha = 0.4)),
        border="gray30",
        names=c("Max", "Min"),
     cex=c2,
     cex.lab=c3,
     cex.axis=c2
)

title("(c)", adj = 0.05, line = 0, cex.main=c3)
```

```{r}
hist(high$length)
hist(low$length)

ggplot(df, aes(length, fill = extreme)) + 
   geom_histogram(alpha = 0.5, aes(y = ..density..), position = 'identity')
```













