---
title: "PCA Exploration"
author: "Acacia Tsz So Tang""
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())

#load packages
require(FactoMineR)
require(factoextra)
require(corrplot)
require(readr)
library(corrplot)

knitr::opts_chunk$set(echo = TRUE)
```

## Reading and Cleaning the Data

```{r}
growthForm <- read.csv("data/growthForm.csv", row.names = 1)
growthForm <- read.csv("data/growthForm2.csv", row.names = 1)
Groupings <- read_csv("data/Groupings.csv")
```

```{r}
source("src/cleaning_data.R")
source("src/regression_output.R")
output_col = FALSE

all_data = clean_data("data/General_Oco_Data2.csv", "data/Terminal_5Segs.csv")

ocos = all_data[[2]]
ocos_baj = ocos[1:20,]
segs = all_data[[1]]
seg_baj = segs[1:1000,] 

segs <- segs[!is.na(segs$Length_c),]
```

## PCA 

```{r}
#for plotting
Round <- function(number){
  x <- round(number, 1)
  if(x%%1 == 0){
    return(paste(as.character(x), ".0", sep = ""))
  }
  else{
    return(x)
  }
}

```

```{r}
PCA_graphs <- function(dataset, PCA_title){
    GFpca <- PCA(dataset, scale.unit = TRUE, graph = TRUE, ncp = 10)
    
    eig.val <- get_eigenvalue(GFpca)
    var.val <- GFpca$var
    print(eig.val) #will only show in in console
    print(var.val)
    
    scree <- fviz_eig(GFpca, addlabels = TRUE, ylim = c(0, 50))
    print(scree)
    
    labX <- paste("PC1 (", Round(eig.val[1, 2]), "%)", sep = "")
    labY <- paste("PC1 (", Round(eig.val[2, 2]), "%)", sep = "")
    leplot <- fviz_pca_biplot(GFpca, geom.id = c("point"), geom.var = c("arrow", "text"), 
                              label = "var", repel = TRUE, col.ind = "gray", col.var = "black")
    ggpubr::ggpar(leplot, title = PCA_title, xlab = labX, ylab = labY, 
                  ggtheme = theme_classic(), font.main = 20, font.x = 14, font.y = 14, font.tickslab = 12)
}
```

### Without IQR Vars:

```{r fig.height=2.5, fig.width=2.6}
# Plant 1 Removed | Without IQR Vars

d = growthForm[-1, c(-5,-6)]
PCA_graphs(d, "(a) ")

colnames(d) = c("Height", "Circ", "NB", "M TSL", "M BL", "Nodes")
D = cor(d)
test <- cor.mtest(d)$p
corrplot.mixed(D,lower.col = "black", number.cex = .7, p.mat=test, sig.level=0.05)
corrplot.mixed(D,lower.col = "black", number.cex = .7)
```

### With IQR Vars:

```{r fig.height=2.5, fig.width=2.6}
# Plant 1 Removed 

d = growthForm[-1, ]
PCA_graphs(d, "(b)")

colnames(d) = c("Height", "Circ", "NB", "M TSL", "TSL IQR", "BL IQR", "M BL", "Nodes")
D = cor(d)
test <- cor.mtest(d)$p
corrplot.mixed(D,lower.col = "black", number.cex = .7, p.mat=test, sig.level=0.05)
corrplot.mixed(D,lower.col = "black", number.cex = .7)
```

This PCA suggests that there is a lot of variation around range, so much so that it apparently drives the PCA when you add it in.

