
### Diagnostic Plot Function

plot_diagnostic = function(m, d) {
  # m:  model generated by lm() or glm()
  # d:  data as a data.frame object
  
  d['fitted_values'] = m$fitted.values
  d['fitted_residuals'] = m$residuals
  
  plot = ggplot(data = d) + geom_point(aes(x = fitted_values, y = fitted_residuals)) +
    geom_hline(yintercept = 0) +
    labs(title = "Plot of Fitted Residuals against Fitted Values",
         x = "Fitted Values", y = "Fitted Residuals") 
  
  print(ols_test_normality(m))
  
  return(plot)
}